//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mathster.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource_cs_CZ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource_cs_CZ() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mathster.Resources.Localization.AppResource.cs-CZ", typeof(AppResource_cs_CZ).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        internal static string Ano {
            get {
                return ResourceManager.GetString("Ano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Délka počítání:.
        /// </summary>
        internal static string CasPocitani {
            get {
                return ResourceManager.GetString("CasPocitani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celkem.
        /// </summary>
        internal static string Celkem {
            get {
                return ResourceManager.GetString("Celkem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Další.
        /// </summary>
        internal static string Dalsi {
            get {
                return ResourceManager.GetString("Dalsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tmavý režim.
        /// </summary>
        internal static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dělení.
        /// </summary>
        internal static string Deleni {
            get {
                return ResourceManager.GetString("Deleni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno:.
        /// </summary>
        internal static string Jmeno {
            get {
                return ResourceManager.GetString("Jmeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úroveň.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Náhodně.
        /// </summary>
        internal static string Nahodne {
            get {
                return ResourceManager.GetString("Nahodne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Násobení.
        /// </summary>
        internal static string Nasobeni {
            get {
                return ResourceManager.GetString("Nasobeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení.
        /// </summary>
        internal static string Nastaveni {
            get {
                return ResourceManager.GetString("Nastaveni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        internal static string Ne {
            get {
                return ResourceManager.GetString("Ne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Aplikaci.
        /// </summary>
        internal static string OAplikaci {
            get {
                return ResourceManager.GetString("OAplikaci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Účelem aplikace je procvičovat a zrychlovat se v počtech. Aplikace je vhodná pro malé i velké počtáře..
        /// </summary>
        internal static string OAplikaciText {
            get {
                return ResourceManager.GetString("OAplikaciText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verze aplikace: .
        /// </summary>
        internal static string OAplikaciVerze {
            get {
                return ResourceManager.GetString("OAplikaciVerze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odečítání.
        /// </summary>
        internal static string Odecitani {
            get {
                return ResourceManager.GetString("Odecitani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odevzdat.
        /// </summary>
        internal static string Odevzdat {
            get {
                return ResourceManager.GetString("Odevzdat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nás.
        /// </summary>
        internal static string ONas {
            get {
                return ResourceManager.GetString("ONas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jsme skupina bláznivých jedinců, co se dívají na věci z jiného úhlu a snaží se posouvat technologie dál..
        /// </summary>
        internal static string ONasText {
            get {
                return ResourceManager.GetString("ONasText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poměr.
        /// </summary>
        internal static string Pomer {
            get {
                return ResourceManager.GetString("Pomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Řešení.
        /// </summary>
        internal static string Reseni {
            get {
                return ResourceManager.GetString("Reseni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jste si jistí, že chcete resetovat statistiky? (Budou navždy pryč).
        /// </summary>
        internal static string ResetMessage {
            get {
                return ResourceManager.GetString("ResetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sčítání.
        /// </summary>
        internal static string Scitani {
            get {
                return ResourceManager.GetString("Scitani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehled.
        /// </summary>
        internal static string Souhrn {
            get {
                return ResourceManager.GetString("Souhrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správné řešení.
        /// </summary>
        internal static string SpravneReseni {
            get {
                return ResourceManager.GetString("SpravneReseni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistiky.
        /// </summary>
        internal static string Statistiky {
            get {
                return ResourceManager.GetString("Statistiky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetovat statistiky.
        /// </summary>
        internal static string StatReset {
            get {
                return ResourceManager.GetString("StatReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozornění.
        /// </summary>
        internal static string Upozorneni {
            get {
                return ResourceManager.GetString("Upozorneni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Všechny výsledky jsou správně. Velká gratulace!.
        /// </summary>
        internal static string UpozorneniVseDobre {
            get {
                return ResourceManager.GetString("UpozorneniVseDobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bohužel, všechny výsledky jsou špatně. Měli by jste více procvičovat..
        /// </summary>
        internal static string UpozorneniVseSpatne {
            get {
                return ResourceManager.GetString("UpozorneniVseSpatne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím zadejte číslo.
        /// </summary>
        internal static string UpozorneniZadejteCislo {
            get {
                return ResourceManager.GetString("UpozorneniZadejteCislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše řešení.
        /// </summary>
        internal static string VaseReseni {
            get {
                return ResourceManager.GetString("VaseReseni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolte velikost čísel.
        /// </summary>
        internal static string VelikostCisel {
            get {
                return ResourceManager.GetString("VelikostCisel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výsledky.
        /// </summary>
        internal static string Vysledky {
            get {
                return ResourceManager.GetString("Vysledky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafika: Martin Borka, Jan Řehoř, Majka P..
        /// </summary>
        internal static string VyvojGrafika {
            get {
                return ResourceManager.GetString("VyvojGrafika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programování: Martin Lahučký.
        /// </summary>
        internal static string VyvojProgramovani {
            get {
                return ResourceManager.GetString("VyvojProgramovani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stiskněte znovu zpět pro ukončení aplikace.
        /// </summary>
        internal static string WarningExit {
            get {
                return ResourceManager.GetString("WarningExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadání.
        /// </summary>
        internal static string Zadani {
            get {
                return ResourceManager.GetString("Zadani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte své jméno.
        /// </summary>
        internal static string ZadejteJmeno {
            get {
                return ResourceManager.GetString("ZadejteJmeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolte dělitel/násobitel.
        /// </summary>
        internal static string ZvolitNasobitelADelitel {
            get {
                return ResourceManager.GetString("ZvolitNasobitelADelitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolte počet příkladů.
        /// </summary>
        internal static string ZvolitPocetPrikladu {
            get {
                return ResourceManager.GetString("ZvolitPocetPrikladu", resourceCulture);
            }
        }
    }
}
