//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mathster.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mathster.Resources.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About application.
        /// </summary>
        internal static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application was designed to practice. .
        /// </summary>
        internal static string AboutAppText {
            get {
                return ResourceManager.GetString("AboutAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are a group of crazy individuals looking at things from a different angle and trying to move technology forward..
        /// </summary>
        internal static string AboutUsText {
            get {
                return ResourceManager.GetString("AboutUsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition.
        /// </summary>
        internal static string Addition {
            get {
                return ResourceManager.GetString("Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t make a single mistake. Congratulations!.
        /// </summary>
        internal static string AlertAllCorrect {
            get {
                return ResourceManager.GetString("AlertAllCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunetly You didn&apos;t have a single exercise right. You should practice more..
        /// </summary>
        internal static string AlertAllWrong {
            get {
                return ResourceManager.GetString("AlertAllWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press back again to exit.
        /// </summary>
        internal static string AlertExit {
            get {
                return ResourceManager.GetString("AlertExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input a number.
        /// </summary>
        internal static string AlertInputNumber {
            get {
                return ResourceManager.GetString("AlertInputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset statistics? (They will be gone forever).
        /// </summary>
        internal static string AlertResetStatistics {
            get {
                return ResourceManager.GetString("AlertResetStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application version.
        /// </summary>
        internal static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment.
        /// </summary>
        internal static string Assignment {
            get {
                return ResourceManager.GetString("Assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the square.
        /// </summary>
        internal static string CompleteTheSquare {
            get {
                return ResourceManager.GetString("CompleteTheSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counting time.
        /// </summary>
        internal static string CountTime {
            get {
                return ResourceManager.GetString("CountTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark mode.
        /// </summary>
        internal static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming: Martin Lahučký.
        /// </summary>
        internal static string DevBackEndText {
            get {
                return ResourceManager.GetString("DevBackEndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface and Graphics: Martin Borka, Jan Řehoř.
        /// </summary>
        internal static string DevFrontEndText {
            get {
                return ResourceManager.GetString("DevFrontEndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        internal static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name.
        /// </summary>
        internal static string EnterYourName {
            get {
                return ResourceManager.GetString("EnterYourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equation.
        /// </summary>
        internal static string Equation {
            get {
                return ResourceManager.GetString("Equation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gianed .
        /// </summary>
        internal static string Gained {
            get {
                return ResourceManager.GetString("Gained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear equation.
        /// </summary>
        internal static string LinearEquation {
            get {
                return ResourceManager.GetString("LinearEquation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication.
        /// </summary>
        internal static string Multiplication {
            get {
                return ResourceManager.GetString("Multiplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadratic equation.
        /// </summary>
        internal static string QuadraticEquation {
            get {
                return ResourceManager.GetString("QuadraticEquation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        internal static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        internal static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset statistics.
        /// </summary>
        internal static string ResetStatistics {
            get {
                return ResourceManager.GetString("ResetStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Divisor/Multiplicator.
        /// </summary>
        internal static string SelectDivMulSize {
            get {
                return ResourceManager.GetString("SelectDivMulSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of exercises.
        /// </summary>
        internal static string SelectExercisesAmount {
            get {
                return ResourceManager.GetString("SelectExercisesAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select number size.
        /// </summary>
        internal static string SelectNumSize {
            get {
                return ResourceManager.GetString("SelectNumSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        internal static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct solution.
        /// </summary>
        internal static string SolutionCorrect {
            get {
                return ResourceManager.GetString("SolutionCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtraction.
        /// </summary>
        internal static string Subtraction {
            get {
                return ResourceManager.GetString("Subtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your solution.
        /// </summary>
        internal static string YourSolution {
            get {
                return ResourceManager.GetString("YourSolution", resourceCulture);
            }
        }
    }
}
