//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mathster.Helpers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mathster.Helpers.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Ano {
            get {
                return ResourceManager.GetString("Ano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of calculated division exercises:.
        /// </summary>
        internal static string CelkemDeleni {
            get {
                return ResourceManager.GetString("CelkemDeleni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of correctly calculated division exercises:.
        /// </summary>
        internal static string CelkemDeleniSpravne {
            get {
                return ResourceManager.GetString("CelkemDeleniSpravne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of calculated multiplication exercises:.
        /// </summary>
        internal static string CelkemNasobeni {
            get {
                return ResourceManager.GetString("CelkemNasobeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of correctly calculated multiplication exercises:.
        /// </summary>
        internal static string CelkemNasobeniSpravne {
            get {
                return ResourceManager.GetString("CelkemNasobeniSpravne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of calculated subtraction exercises:.
        /// </summary>
        internal static string CelkemOdcitani {
            get {
                return ResourceManager.GetString("CelkemOdcitani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of correctly calculated subtraction exercises:.
        /// </summary>
        internal static string CelkemOdcitaniSpravne {
            get {
                return ResourceManager.GetString("CelkemOdcitaniSpravne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of calculated exercises:.
        /// </summary>
        internal static string CelkemPrikladu {
            get {
                return ResourceManager.GetString("CelkemPrikladu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of correctly calculated exercises:.
        /// </summary>
        internal static string CelkemPrikladuDobre {
            get {
                return ResourceManager.GetString("CelkemPrikladuDobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of calculated addition exercises:.
        /// </summary>
        internal static string CelkemScitani {
            get {
                return ResourceManager.GetString("CelkemScitani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of correctly calculated addition exercises:.
        /// </summary>
        internal static string CelkemScitaniSpravne {
            get {
                return ResourceManager.GetString("CelkemScitaniSpravne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four digit.
        /// </summary>
        internal static string Ctyrciferne {
            get {
                return ResourceManager.GetString("Ctyrciferne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Dalsi {
            get {
                return ResourceManager.GetString("Dalsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        internal static string Deleni {
            get {
                return ResourceManager.GetString("Deleni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to 10.
        /// </summary>
        internal static string DoDeseti {
            get {
                return ResourceManager.GetString("DoDeseti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to 20.
        /// </summary>
        internal static string DoDvaceti {
            get {
                return ResourceManager.GetString("DoDvaceti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to 5.
        /// </summary>
        internal static string DoPeti {
            get {
                return ResourceManager.GetString("DoPeti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most frequently calculated type of exercise:.
        /// </summary>
        internal static string DruhNejcastejiPocitanychPrikladu {
            get {
                return ResourceManager.GetString("DruhNejcastejiPocitanychPrikladu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double digit.
        /// </summary>
        internal static string Dvouciferne {
            get {
                return ResourceManager.GetString("Dvouciferne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single digit.
        /// </summary>
        internal static string Jednociferne {
            get {
                return ResourceManager.GetString("Jednociferne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string Jmeno {
            get {
                return ResourceManager.GetString("Jmeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total distance traveled:.
        /// </summary>
        internal static string Nachozeno {
            get {
                return ResourceManager.GetString("Nachozeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        internal static string Nahodne {
            get {
                return ResourceManager.GetString("Nahodne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication.
        /// </summary>
        internal static string Nasobeni {
            get {
                return ResourceManager.GetString("Nasobeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Nastaveni {
            get {
                return ResourceManager.GetString("Nastaveni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Ne {
            get {
                return ResourceManager.GetString("Ne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine.
        /// </summary>
        internal static string NelzeUrcit {
            get {
                return ResourceManager.GetString("NelzeUrcit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Application.
        /// </summary>
        internal static string OAplikaci {
            get {
                return ResourceManager.GetString("OAplikaci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application was designed to practice so that even more complex numbers can be handled easily and you do not have to constantly reach for a calculator..
        /// </summary>
        internal static string OAplikaciText {
            get {
                return ResourceManager.GetString("OAplikaciText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application version: .
        /// </summary>
        internal static string OAplikaciVerze {
            get {
                return ResourceManager.GetString("OAplikaciVerze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtraction.
        /// </summary>
        internal static string Odecitani {
            get {
                return ResourceManager.GetString("Odecitani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Odevzdat {
            get {
                return ResourceManager.GetString("Odevzdat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string ONas {
            get {
                return ResourceManager.GetString("ONas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are a group of crazy individuals looking at things from a different angle and trying to move technology forward..
        /// </summary>
        internal static string ONasText {
            get {
                return ResourceManager.GetString("ONasText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five digit.
        /// </summary>
        internal static string Peticiferne {
            get {
                return ResourceManager.GetString("Peticiferne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the number of exercises.
        /// </summary>
        internal static string PocetPrikladu {
            get {
                return ResourceManager.GetString("PocetPrikladu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Predchozi {
            get {
                return ResourceManager.GetString("Predchozi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        internal static string Reseni {
            get {
                return ResourceManager.GetString("Reseni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset statistics? (They will be gone forever).
        /// </summary>
        internal static string ResetMessage {
            get {
                return ResourceManager.GetString("ResetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition.
        /// </summary>
        internal static string Scitani {
            get {
                return ResourceManager.GetString("Scitani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Six digit.
        /// </summary>
        internal static string Seticiferne {
            get {
                return ResourceManager.GetString("Seticiferne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Souhrn {
            get {
                return ResourceManager.GetString("Souhrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong.
        /// </summary>
        internal static string Spatne {
            get {
                return ResourceManager.GetString("Spatne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        internal static string Spravne {
            get {
                return ResourceManager.GetString("Spravne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answer.
        /// </summary>
        internal static string SpravneReseni {
            get {
                return ResourceManager.GetString("SpravneReseni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistiky {
            get {
                return ResourceManager.GetString("Statistiky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset statistics.
        /// </summary>
        internal static string StatReset {
            get {
                return ResourceManager.GetString("StatReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three digit.
        /// </summary>
        internal static string Trojciferne {
            get {
                return ResourceManager.GetString("Trojciferne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Upozorneni {
            get {
                return ResourceManager.GetString("Upozorneni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t make a single mistake. Congratulations!.
        /// </summary>
        internal static string UpozorneniVseDobre {
            get {
                return ResourceManager.GetString("UpozorneniVseDobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunetly You didn&apos;t have a single exercise right. You should practice more..
        /// </summary>
        internal static string UpozorneniVseSpatne {
            get {
                return ResourceManager.GetString("UpozorneniVseSpatne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input a number.
        /// </summary>
        internal static string UpozorneniZadejteCislo {
            get {
                return ResourceManager.GetString("UpozorneniZadejteCislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success rate.
        /// </summary>
        internal static string Uspesnost {
            get {
                return ResourceManager.GetString("Uspesnost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answer.
        /// </summary>
        internal static string VaseReseni {
            get {
                return ResourceManager.GetString("VaseReseni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select number size.
        /// </summary>
        internal static string VelikostCisel {
            get {
                return ResourceManager.GetString("VelikostCisel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of all the first numbers.
        /// </summary>
        internal static string VelikostVsechPrvnichCisel {
            get {
                return ResourceManager.GetString("VelikostVsechPrvnichCisel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Vysledky {
            get {
                return ResourceManager.GetString("Vysledky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface and Graphics: Martin Borka, Jan Řehoř.
        /// </summary>
        internal static string VyvojGrafika {
            get {
                return ResourceManager.GetString("VyvojGrafika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming: Martin Lahučký.
        /// </summary>
        internal static string VyvojProgramovani {
            get {
                return ResourceManager.GetString("VyvojProgramovani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name.
        /// </summary>
        internal static string ZadejteJmeno {
            get {
                return ResourceManager.GetString("ZadejteJmeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points gained.
        /// </summary>
        internal static string ZiskaneBody {
            get {
                return ResourceManager.GetString("ZiskaneBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Multiplicator and Divisor.
        /// </summary>
        internal static string ZvolitNasobitelADelitel {
            get {
                return ResourceManager.GetString("ZvolitNasobitelADelitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of exercises.
        /// </summary>
        internal static string ZvolitPocetPrikladu {
            get {
                return ResourceManager.GetString("ZvolitPocetPrikladu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Divisitor.
        /// </summary>
        internal static string ZvolteDelitele {
            get {
                return ResourceManager.GetString("ZvolteDelitele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Multiplicator.
        /// </summary>
        internal static string ZvolteNasobitele {
            get {
                return ResourceManager.GetString("ZvolteNasobitele", resourceCulture);
            }
        }
    }
}
